spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 阿里云oss配置
    alicloud:
      access-key: accessKeyId
      secret-key: accessKeySecret
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: aliyunoss-wwx

server:
  port: 30000